cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2130_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2130_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1490_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1490_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2139_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2139_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN892_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN892_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1968_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1968_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN781_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN781_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN468_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN468_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1473_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1473_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN701_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN701_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN936_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN936_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1352_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1352_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN900_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN900_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN825_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN825_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1416_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1416_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1761_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1761_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1691_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1691_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1644_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1644_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1562_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1562_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1465_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1465_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN801_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN801_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1923_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1923_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1657_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1657_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN459_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN459_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1086_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1086_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2187_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2187_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN290_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN290_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1483_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1483_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2149_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2149_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1037_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1037_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1646_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1646_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1358_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1358_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1946_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1946_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1863_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1863_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1829_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1829_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1686_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1686_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1061_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1061_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN498_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN498_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1623_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1623_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1819_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1819_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1849_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1849_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2058_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2058_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2004_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2004_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN564_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN564_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1340_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1340_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1695_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1695_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1368_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1368_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1628_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1628_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1509_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1509_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN915_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN915_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1610_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1610_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN551_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN551_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2150_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2150_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1572_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1572_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN999_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN999_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1334_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1334_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1696_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1696_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN767_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN767_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1575_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1575_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1384_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1384_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2064_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2064_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1747_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1747_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN691_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN691_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1289_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1289_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN788_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN788_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1447_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1447_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1207_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1207_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2127_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2127_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2181_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2181_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1765_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1765_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1643_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1643_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2148_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2148_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN377_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN377_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1808_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1808_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2179_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2179_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN807_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN807_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN869_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN869_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1339_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1339_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2075_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2075_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1085_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1085_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2213_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2213_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2137_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2137_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN523_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN523_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN280_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN280_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1779_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1779_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2105_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2105_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1702_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1702_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1399_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1399_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1000_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1000_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN339_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN339_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN467_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN467_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1462_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1462_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1885_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1885_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1219_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1219_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1395_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1395_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2144_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2144_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN848_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN848_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1567_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1567_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2089_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2089_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN105_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN105_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1006_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1006_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2034_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2034_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1058_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1058_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN147_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN147_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN31_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN31_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2083_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2083_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1961_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1961_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1818_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1818_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN968_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN968_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1776_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1776_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN653_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN653_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN489_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN489_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2205_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2205_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN460_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN460_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN408_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN408_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1679_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1679_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1661_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1661_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN300_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN300_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1364_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1364_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1663_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1663_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN731_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN731_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN657_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN657_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2166_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2166_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1540_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1540_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1020_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1020_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1858_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1858_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1253_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1253_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2178_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2178_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN359_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN359_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2221_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2221_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN317_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN317_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN142_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN142_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1151_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1151_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1731_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1731_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1082_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1082_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1038_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1038_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1442_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1442_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1645_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1645_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1952_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1952_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1732_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1732_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1593_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1593_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN596_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN596_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN244_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN244_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN152_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN152_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1981_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1981_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1844_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1844_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN56_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN56_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1531_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1531_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1430_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1430_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1902_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1902_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1088_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1088_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1834_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1834_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN47_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN47_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN929_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN929_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1743_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1743_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN973_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN973_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1214_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1214_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN62_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN62_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN613_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN613_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1974_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1974_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1413_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1413_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1869_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1869_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1499_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1499_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN2123_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN2123_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN568_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN568_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN1729_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN1729_fixed.fna
cp /home/acampbe/DFU/data/WGS_2020/PhageResults/FNAs/DORN189_DBSCAN-SWA_prophage.fna /home/acampbe/DFU/data/WGS_2020/PhageResults/FixedFNAs/DORN189_fixed.fna
