#!bin/bash
# Calls snp-sites on Mafft alignment of genes 
###############################################
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_group_2670 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_group_2670
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_nusB /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_nusB
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_der_2 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_der_2
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_nirQ /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_nirQ
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_pdhD /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_pdhD
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_group_3007 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_group_3007
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_gluD /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_gluD
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_mnhD1_2 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_mnhD1_2
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_group_4069 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_group_4069
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_dtpT /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_dtpT
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_group_2849 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_group_2849
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_group_3720 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_group_3720
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_rpoC /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_rpoC
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_secE /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_secE
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_wbpI /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_wbpI
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_group_3821 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_group_3821
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_yefM /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_yefM
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_group_3583 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_group_3583
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_sdrM /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_sdrM
snp-sites -v -o /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/SNPs_ssbA_3 /home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/Patient191/GeneFastas/MAFFT/Mafft_ssbA_3
