# Amy Campbell
# 3/26/23 Running WhatsGNU main script on the reference genomes I want to include for patient 191 plotter call

source ~/mambaforge/bin/activate ~/mambaforge/envs/WhatsGNUEnv

StaphDB=/home/acampbe/DownloadedDatabases/WhatsGNU_Sau_Ortholog/Sau_Ortholog_10350.pickle
roaryclusters=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/roary_alignment/results/clustered_proteins
inputfolder=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/
outputfolder=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/WG_reports/

mkdir -p $outputfolder

Remove1334="DORN1334"

# Move all WG reports generated by cladebreaker into the WG report folder, and then remove 1334 because we're ignoring it for this exercise
find $inputfolder -name '*WhatsGNU_report.txt' | xargs cp -t $outputfolder
rm $outputfolder$Remove1334*

# 1. GCA_001019375.2
input1=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/GCA_001019375.2/annotation/GCA_001019375.2.faa
output1=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/GCA_001019375.2/WhatsGNU
WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output1 $input1
wgreport1="/GCA_001019375.2_WhatsGNU_report.txt"
cp $output1$wgreport1 $outputfolder


# 2. GCA_002554295.1 
input2=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/GCA_002554295.1/annotation/GCA_002554295.1.faa
output2=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/GCA_002554295.1/WhatsGNU
WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output2 $input2
wgreport2="/GCA_002554295.1_WhatsGNU_report.txt"                
cp $output2$wgreport2 $outputfolder

# 3. GCA_000597965.1
input3=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/GCA_000597965.1/annotation/GCA_000597965.1.faa
output3=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/GCA_000597965.1/WhatsGNU
WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output3 $input3
wgreport3="/GCA_000597965.1_WhatsGNU_report.txt"
cp $output3$wgreport3 $outputfolder

# 4. GCA_001018775.2
input4=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/GCA_001018775.2/annotation/GCA_001018775.2.faa
output4=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_191/GCA_001018775.2/WhatsGNU
WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output4 $input4
wgreport4="/GCA_001018775.2_WhatsGNU_report.txt"
cp $output4$wgreport4 $outputfolder






