# Amy Campbell
# 3/26/23 Running WhatsGNU main script on the reference genomes I want to include for patient 145 plotter call

source ~/mambaforge/bin/activate ~/mambaforge/envs/WhatsGNUEnv

StaphDB=/home/acampbe/DownloadedDatabases/WhatsGNU_Sau_Ortholog/Sau_Ortholog_10350.pickle
roaryclusters=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/roary_alignment/results/clustered_proteins
inputfolder=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/
outputfolder=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/WG_reports/

mkdir -p $outputfolder

# Move all WG reports generated by cladebreaker into the WG report folder, and then remove 1334 because we're ignoring it for this exercise
find $inputfolder -name '*WhatsGNU_report.txt' | xargs cp -t $outputfolder

# 1. GCA_000011265.1
input1=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000011265.1/annotation/GCA_000011265.1.faa
output1=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000011265.1/WhatsGNU
WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output1 $input1
wgreport1="/GCA_000011265.1_WhatsGNU_report.txt"
cp $output1$wgreport1 $outputfolder

exit 0

# 2. GCA_000248655.2 
input2=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000248655.2/annotation/GCA_000248655.2.faa
output2=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000248655.2/WhatsGNU
#WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output2 $input2
wgreport2="/GCA_000248655.2_WhatsGNU_report.txt"                
#cp $output2$wgreport2 $outputfolder



# 3. GCA_000149015.1
input3=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000149015.1/annotation/GCA_000149015.1.faa
output3=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000149015.1/WhatsGNU
#WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output3 $input3
wgreport3="/GCA_000149015.1_WhatsGNU_report.txt"
#cp $output3$wgreport3 $outputfolder


# 4. GCA_003336555.1
input4=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_003336555.1/annotation/GCA_003336555.1.faa
output4=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_003336555.1/WhatsGNU
#WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output4 $input4
wgreport4="/GCA_003336555.1_WhatsGNU_report.txt"
#cp $output4$wgreport4 $outputfolder


# 5. GCA_001019175.2
input5=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_001019175.2/annotation/GCA_001019175.2.faa
output5=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_001019175.2/WhatsGNU
#WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output5 $input5
wgreport5="/GCA_001019175.2_WhatsGNU_report.txt"
#cp $output5$wgreport5 $outputfolder



# 6. GCA_000248535.2
input6=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000248535.2/annotation/GCA_000248535.2.faa
output6=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000248535.2/WhatsGNU
#WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output6 $input6
wgreport6="/GCA_000248535.2_WhatsGNU_report.txt"
#cp $output6$wgreport6 $outputfolder



# 7. GCA_000772025.1
input7=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000772025.1/annotation/GCA_000772025.1.faa
output7=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_000772025.1/WhatsGNU
#WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output7 $input7
wgreport7="/GCA_000772025.1_WhatsGNU_report.txt"
#cp $output7$wgreport7 $outputfolder


# 8. GCA_900637155.1
input8=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_900637155.1/annotation/GCA_900637155.1.faa
output8=/home/acampbe/DFU/data/WGS_2020/cladebreaker/cladebreaker_patient_145/GCA_900637155.1/WhatsGNU
#WhatsGNU_main.py -d $StaphDB -dm ortholog -o $output8 $input8
wgreport8="/GCA_900637155.1_WhatsGNU_report.txt"
#cp $output8$wgreport8 $outputfolder

