#!/bin/bash
mkdir -p /home/acampbe/DFU/data/WGS_2020/RoaryResults
source /home/acampbe/software/miniconda3/bin/activate prokenv
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2179 --force --prefix DORN2179 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2179_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1572 --force --prefix DORN1572 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1572_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN976 --force --prefix DORN976 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN976_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1037 --force --prefix DORN1037 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1037_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2221 --force --prefix DORN2221 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2221_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1219 --force --prefix DORN1219 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1219_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1038 --force --prefix DORN1038 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1038_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN701 --force --prefix DORN701 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN701_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN882 --force --prefix DORN882 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN882_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2205 --force --prefix DORN2205 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2205_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2150 --force --prefix DORN2150 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2150_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1483 --force --prefix DORN1483 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1483_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1465 --force --prefix DORN1465 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1465_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1061 --force --prefix DORN1061 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1061_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1623 --force --prefix DORN1623 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1623_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN685 --force --prefix DORN685 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN685_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1858 --force --prefix DORN1858 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1858_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2139 --force --prefix DORN2139 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2139_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1509 --force --prefix DORN1509 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1509_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN781 --force --prefix DORN781 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN781_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN317 --force --prefix DORN317 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN317_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2004 --force --prefix DORN2004 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2004_cleaned.fasta
