#!/bin/bash
mkdir -p /home/acampbe/DFU/data/WGS_2020/RoaryResults
source /home/acampbe/software/miniconda3/bin/activate prokenv
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN825 --force --prefix DORN825 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN825_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN657 --force --prefix DORN657 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN657_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN933 --force --prefix DORN933 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN933_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1410 --force --prefix DORN1410 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1410_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2166 --force --prefix DORN2166 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2166_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1447 --force --prefix DORN1447 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1447_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1455 --force --prefix DORN1455 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1455_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1755 --force --prefix DORN1755 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1755_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1496 --force --prefix DORN1496 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1496_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2109 --force --prefix DORN2109 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2109_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1413 --force --prefix DORN1413 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1413_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1646 --force --prefix DORN1646 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1646_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2137 --force --prefix DORN2137 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2137_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN429 --force --prefix DORN429 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN429_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN973 --force --prefix DORN973 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN973_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1943 --force --prefix DORN1943 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1943_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN596 --force --prefix DORN596 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN596_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1644 --force --prefix DORN1644 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1644_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1722 --force --prefix DORN1722 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1722_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1442 --force --prefix DORN1442 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1442_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN434 --force --prefix DORN434 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN434_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN147 --force --prefix DORN147 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN147_cleaned.fasta
