#!/bin/bash
mkdir -p /home/acampbe/DFU/data/WGS_2020/completed_prokka
source /home/acampbe/software/miniconda3/bin/activate prokenv
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC1-ST188 --force --prefix CC1-ST188 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC1-ST188_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC133 --force --prefix CC133 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC133_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/USA400_051 --force --prefix USA400_051 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/USA400_051_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC97_ATCC6538 --force --prefix CC97_ATCC6538 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC97_ATCC6538_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC45 --force --prefix CC45 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC45_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC12 --force --prefix CC12 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC12_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC7 --force --prefix CC7 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC7_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC22_HO --force --prefix CC22_HO --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC22_HO_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC1_MSSA476 --force --prefix CC1_MSSA476 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC1_MSSA476_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/SA_502A --force --prefix SA_502A --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/SA_502A_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC97_Newbould305 --force --prefix CC97_Newbould305 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC97_Newbould305_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/USA100_AR465 --force --prefix USA100_AR465 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/USA100_AR465_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC5_N315 --force --prefix CC5_N315 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC5_N315_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/ST20 --force --prefix ST20 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/ST20_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC80 --force --prefix CC80 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC80_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC8_Newman --force --prefix CC8_Newman --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC8_Newman_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC72_CN1 --force --prefix CC72_CN1 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC72_CN1_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC59 --force --prefix CC59 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC59_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC1_MW2 --force --prefix CC1_MW2 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC1_MW2_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC5_Mu50 --force --prefix CC5_Mu50 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC5_Mu50_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/S_epidermidis --force --prefix S_epidermidis --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/S_epidermidis_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/USA300_FPR3757 --force --prefix USA300_FPR3757 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/USA300_FPR3757_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/SA_AR464 --force --prefix SA_AR464 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/SA_AR464_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC8_NCTC8325 --force --prefix CC8_NCTC8325 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC8_NCTC8325_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC398 --force --prefix CC398 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC398_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC30_MRSA252 --force --prefix CC30_MRSA252 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC30_MRSA252_pgap.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/completed_prokka/gff_files/CC15 --force --prefix CC15 --genus Staphylococcus /home/acampbe/DFU/data/WGS_2020/PGAPformattedIsolates/References/CC15_pgap.fasta
