#!/bin/bash
mkdir -p /home/acampbe/DFU/data/WGS_2020/RoaryResults
source /home/acampbe/software/miniconda3/bin/activate prokenv
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1000 --force --prefix DORN1000 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1000_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1628 --force --prefix DORN1628 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1628_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN962 --force --prefix DORN962 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN962_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1499 --force --prefix DORN1499 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1499_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1731 --force --prefix DORN1731 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1731_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1027 --force --prefix DORN1027 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1027_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN408 --force --prefix DORN408 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN408_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN936 --force --prefix DORN936 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN936_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1968 --force --prefix DORN1968 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1968_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN523 --force --prefix DORN523 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN523_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1531 --force --prefix DORN1531 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1531_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN22 --force --prefix DORN22 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN22_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1686 --force --prefix DORN1686 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1686_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1981 --force --prefix DORN1981 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1981_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1151 --force --prefix DORN1151 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1151_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN243 --force --prefix DORN243 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN243_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1395 --force --prefix DORN1395 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1395_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1082 --force --prefix DORN1082 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1082_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1702 --force --prefix DORN1702 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1702_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN290 --force --prefix DORN290 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN290_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN717 --force --prefix DORN717 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN717_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1340 --force --prefix DORN1340 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1340_cleaned.fasta
