#!/bin/bash
mkdir -p /home/acampbe/DFU/data/WGS_2020/RoaryResults
source /home/acampbe/software/miniconda3/bin/activate prokenv
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1368 --force --prefix DORN1368 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1368_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2058 --force --prefix DORN2058 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2058_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN946 --force --prefix DORN946 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN946_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN788 --force --prefix DORN788 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN788_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN880 --force --prefix DORN880 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN880_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1961 --force --prefix DORN1961 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1961_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1863 --force --prefix DORN1863 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1863_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1695 --force --prefix DORN1695 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1695_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1334 --force --prefix DORN1334 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1334_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN251 --force --prefix DORN251 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN251_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1540 --force --prefix DORN1540 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1540_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN2148 --force --prefix DORN2148 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN2148_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1562 --force --prefix DORN1562 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1562_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1194 --force --prefix DORN1194 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1194_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1081 --force --prefix DORN1081 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1081_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1657 --force --prefix DORN1657 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1657_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN315 --force --prefix DORN315 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN315_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN672 --force --prefix DORN672 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN672_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN489 --force --prefix DORN489 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN489_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1808 --force --prefix DORN1808 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1808_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN283 --force --prefix DORN283 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN283_cleaned.fasta
prokka --outdir /home/acampbe/DFU/data/WGS_2020/RoaryResults/gff_files/DORN1546 --force --prefix DORN1546 --genus Staphylococcus /project/grice/storage/HiSeq/WGS/HiSeq_19/AssemblyFastas/DFU100_Cleaned_Assemblies/FinalContigs/DORN1546_cleaned.fasta
